name: Dependency review
on: pull_request
permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Dependency review step
        uses: actions/dependency-review-action@v4.5.0
        with:
          comment-summary-in-pr: always
          
      
    
